title: RapTCR remplate
description: My starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://vincentvandeuren.github.io/RapTCR

aux_links:
  GitHub Repository: https://github.com/vincentvandeuren/RapTCR

